Updated RAKE.py
Changed encoding to 'utf8' for opening the text files since i was using rake for more than 25+ languages (turkish, polish, portuguese, romanian, russian, ...) and stored stop words of each file in .txt file so while running program there was an error like : 

UnicodeDecodeError: 'charmap' codec can't decode byte X in position Y: character maps to <undefined>
After making it 'utf8' it was resolved.